baseurl = "/"
languageCode = "en-us"
title = "APSCRN"

[params]
  name = "APSCRN"
  nameLong = "Australasian Paediatric Sonographers Collaboration and Research Network"
  tagline = "We are an enthusiastic team of paediatric sonographers with a passion for research."
  heroTitle = "Have a bright idea?"
  heroText = "The Australasian Paediatric Sonographers Collaboration and Research Network (APSCRN) is the place to find potential collaborators, seek advice, promote research, and share ideas about paediatric sonography in Australia and New Zealand"
  whatText = "While we might work separately and in different clinical environments, much of what we do in children's ultrasound is in common. This is a network through which paediatric sonographers can share ideas, explore potential collaborations, and promote research. Our aim is to improve the profile of paediatric sonographers and the standard of paediatric ultrasound in the region."
  whoTitile = "Who are we?"
  whoText = "Whilst it's very early days, ideally the core of our network will include at least one sonographer from the major children's hospitals around Australia and New Zealand. Other sonographers that have an interest in paediatrics are also welcome to contribute."
  metaTitle = "Australasian Paediatric Sonographers Collaboration and Research Network"
  metaDescription = "APSCRN are an enthusiastic team of paediatric sonographers with a passion for research."
  faq1 = "What is APSCRN?"
  faa1 = "APSCRN is a network of paediatric sonographers from across Australia and New Zealand designed to provide a platform through which members can share ideas, seek advice, explore potential collaborations, and promote their research."
  faq2 = "Who should join APSCRN?"
  faa2 = "If you’re a sonographer with a particular interest in paediatric ultrasound or working in a tertiary children’s hospital, then pop and have a look."
  faq3 = "How do I join?"
  faa3 = "Send an email to admin@apscrn.org with your name and workplace and you’ll get an invitation to join the Slack “team”."
  faq4 = "Does it cost anything to join?"
  faa4 = "No, nothing. It's totally free to join."
  locale = "Australia"
  localeCode = "AU"
  author = "STOQE"
  twitter = "APSCRN"
  email = "admin@apscrn.org"
  slack = "https://apscrn.slack.com"
  copyright = "Copyright (c) 2017, APSCRN; all rights reserved."
  fourohfourtitle = "Page not found (404 Error)"
  fourohfourmsg = "Return home"